backend:
  name: github
  repo: inambe/inambe-webpage
  branch: staging # Branch to update (optional; defaults to master)
media_folder: static/assets
public_folder: /assets
collections:
  - name: projects
    label: Projects
    label_singular: Project
    folder: content/projects
    create: true
    fields:
      - { label: Title, name: title }
      - { label: Description, name: description }
      - { label: Thumbnail, name: thumbnail, widget: image }
      - { label: Body, name: body, widget: markdown, required: false }
      - label: Uses
        name: uses
        widget: select
        multiple: true
        min: 1
        options: ["PHP", "JavaScript", "React", "Node.js", "HTML/CSS", "Express", "Flutter", "Dart", "Mobile"]
      - { label: Source Link, name: source_link, required: false }
      - { label: Live Link, name: live_link, required: false }
      - { label: Created, name: date, widget: datetime, time_format: false, date_format: "YYYY-MM-DD" }